INSERT INTO t_customer (name, email) VALUES ('test', 'test@test.com');

INSERT INTO t_category (name)
VALUES ('smartphones'),
('laptops'),
('fragrances'),
('skincare'),
('groceries'),
('home-decoration'),
('furniture'),
('tops'),
('womens-dresses'),
('womens-shoes'),
('mens-shirts'),
('mens-shoes'),
('mens-watches'),
('womens-watches'),
('womens-bags'),
('womens-jewellery'),
('sunglasses'),
('automotive'),
('motorcycle'),
('lighting');

INSERT INTO t_product (title, description, price, quantity, image_url, category_id)
VALUES
('iPhone 9', 'An apple mobile which is nothing like apple', 549, 94, 'https://i.dummyjson.com/data/products/1/1.jpg', 1),
('iPhone X', 'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...', 899, 34, 'https://i.dummyjson.com/data/products/2/1.jpg', 1),
('Samsung Universe 9', 'Samsung''s new variant which goes beyond Galaxy to the Universe', 1249, 36, 'https://i.dummyjson.com/data/products/3/1.jpg', 1),
('OPPOF19', 'OPPO F19 is officially announced on April 2021.', 280, 123, 'https://i.dummyjson.com/data/products/4/1.jpg', 1),
('Huawei P30', 'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.', 499, 32, 'https://i.dummyjson.com/data/products/5/1.jpg', 1),
('MacBook Pro', 'MacBook Pro 2021 with mini-LED display may launch between September, November', 1749, 83, 'https://i.dummyjson.com/data/products/6/1.png', 2),
('Samsung Galaxy Book', 'Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched', 1499, 50, 'https://i.dummyjson.com/data/products/7/1.jpg', 2),
('Microsoft Surface Laptop 4', 'Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.', 1499, 68, 'https://i.dummyjson.com/data/products/8/1.jpg', 2),
('Infinix INBOOK', 'Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty', 1099, 96, 'https://i.dummyjson.com/data/products/9/1.jpg', 2),
('HP Pavilion 15-DK1056WM', 'HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10', 1099, 89, 'https://i.dummyjson.com/data/products/10/1.jpg', 2),
('perfume Oil', 'Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil', 13, 65, 'https://i.dummyjson.com/data/products/11/1.jpg', 3),
('Brown Perfume', 'Royal_Mirage Sport Brown Perfume for Men & Women - 120ml', 40, 52, 'https://i.dummyjson.com/data/products/12/1.jpg', 3),
('Fog Scent Xpressio Perfume', 'Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men', 13, 61, 'https://i.dummyjson.com/data/products/13/1.jpg', 3),
('Non-Alcoholic Concentrated Perfume Oil', 'Original Al Munakh® by Mahal Al Musk | Our Impression of Climate |6ml Non-Alcoholic Concentrated Perfume Oil', 120, 114, 'https://i.dummyjson.com/data/products/14/1.jpg', 3),
('Eau De Perfume Spray', 'Genuine Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality', 30, 105, 'https://i.dummyjson.com/data/products/15/1.jpg', 3),
('Hyaluronic Acid Serum', 'L''Oréal Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid', 19, 110, 'https://i.dummyjson.com/data/products/16/1.png', 4),
('Tree Oil 30ml', 'Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,', 12, 78, 'https://i.dummyjson.com/data/products/17/1.jpg', 4),
('Oil Free Moisturizer 100ml', 'Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.', 40, 88, 'https://i.dummyjson.com/data/products/18/1.jpg', 4),
('Skin Beauty Serum.', 'Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m', 46, 54, 'https://i.dummyjson.com/data/products/19/1.jpg', 4),
('Freckle Treatment Cream- 15gm', 'Fair & Clear is Pakistan''s only pure Freckle cream which helps fade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.', 70, 140, 'https://i.dummyjson.com/data/products/20/1.jpg', 4),
('Daal Masoor 500 grams', 'Fine quality Branded Product Keep in a cool and dry place', 20, 133, 'https://i.dummyjson.com/data/products/21/1.png', 5),
('Elbow Macaroni - 400 gm', 'Product details of Bake Parlor Big Elbow Macaroni - 400 gm', 14, 146, 'https://i.dummyjson.com/data/products/22/1.jpg', 5),
('Orange Esence Food Flavou', 'Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item', 14, 26, 'https://i.dummyjson.com/data/products/23/1.jpg', 5),
('cereals muesli fruit nuts', 'original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji', 46, 113, 'https://i.dummyjson.com/data/products/24/1.jpg', 5),
('Gulab Powder 50 Gram', 'Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds', 70, 47, 'https://i.dummyjson.com/data/products/25/1.png', 5),
('Plant Hanger For Home', 'Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf', 41, 131, 'https://i.dummyjson.com/data/products/26/1.jpg', 6),
('Flying Wooden Bird', 'Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm', 51, 17, 'https://i.dummyjson.com/data/products/27/1.jpg', 6),
('3D Embellishment Art Lamp', '3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)', 20, 54, 'https://i.dummyjson.com/data/products/28/1.jpg', 6),
('Handcraft Chinese style', 'Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate', 60, 7, 'https://i.dummyjson.com/data/products/29/1.jpg', 6),
('Key Holder', 'Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality', 30, 54, 'https://i.dummyjson.com/data/products/30/1.jpg', 6);
